### ISSUE TITLE
Cross attention wrong query vector

### ISSUE THREAD

**Issue by wj210** [lucidrains/block-recurrent-transformer-pytorch#2]
Hi, in the AttentionBlock forward function, the vertical attention is computing cross-attention with Qe^v instead of Qs^v? Same goes for the horizontal direction, it is computing using Qs^h instead of Qe^h.

**Comment by wj210** [comment]
Also, to add on to the previous question, is there any reason why the q,k,v  of recurrent state for horizontal attention direction computing used self.init_state, rather than states, which is the current state.
Thanks!

**Comment by lucidrains** [comment]
yeah, I think for vertical, the queries are projected from the embeddings, but attends to key and values from state. the other way around for horizontal. notation is kinda funny (I think the subscript refers to what it will attend to)

init state should only be used on the first forward, when no states are passed in
