### ISSUE TITLE
It seems line 942 states = [] is override  states from params

### ISSUE THREAD

**Issue by junphine** [lucidrains/block-recurrent-transformer-pytorch#6]
def generate(
        self,
        prime,
        length = None,
        xl_memories: List[torch.Tensor] = [],
        states: List[torch.Tensor] = [],
        temperature = 1.,
        filter_thres = 0.9,
        return_memories_and_states = False
    ):
        length = default(length, self.max_seq_len + 1)
        start_len = prime.shape[-1]

        assert start_len < self.max_seq_len
        assert length <= (self.max_seq_len + 1)
        assert start_len < length

        output = prime

        memories = []
        states = []

        for ind in range(length - start_len):

**Comment by lucidrains** [comment]
@junphine :man_facepalming: thanks! https://github.com/lucidrains/block-recurrent-transformer-pytorch/commit/b22f552ccb5126e2a0688039076bf7b8de5a5016
